spring:
  application:
    name: internet-banking-fund-transfer-service
  datasource:
    url: jdbc:mysql://localhost:3306/banking_core_fund_transfer_service
    username: root
    password: Welcome@#123!
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 9094

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9091/eureka
info:
  app:
    name: ${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: "*"